```python
df.merge(right,how='left',on=None)
```
right(인수 데이터프레임 혹은 시리즈): 병합할 객체

how(인수는 'left','right','outer','inner','cross')
병합할 방식을 결정하는 인자


on(인수는 열의 레이블 또는 리스트)
병합의 기준이 되는 열을 지정하는 인자

In [2]:
import pandas as pd;

In [ ]:
pd.set_option('display.max_rows',6)
data1= [['송중기','별다방','아이스티'],
        ['권나현','콩다방','카페오레'],
        ['권보아','별다방','카페오레'],
        ['박효신','콩다방','아이스티'],
        ['김점수','별다방','카페오레']]
data2 = [['별다방','아이스티',4500],
        ['별다방','카페오레',4000],
        ['콩다방','아이스티',6000],
        ['콩다방','아이스티',6000],
        ['콩다방','카페오레',5500]]

df1 = pd.DataFrame(data1, columns=['이름','업체','음료'])
df2 = pd.DataFrame(data2, columns=['업체','음료','가격'])

```python
df.rename(index=None,coloumns=None,level=None)
```

### **index**(인수는 mapper)
> index의 이름을 바꾸는 인자
- mapper란? 딕셔너리나 시리즈나 함수와 같이 맵핑을 할수 있는 매개체

### **coloumns**(인수는 mapper)
> cloumns의 이름을 바꾸는 인자

### **level**(인수는 level의 로케이션 혹은 레이블 / 기본값은 None)
> 멀티인덱스에서 이름을 바꿀 레벨을 지정하는 인자. 기본값은 모든 level에서 이름을 바꾼다.


#### 맵퍼(mapper)란?
> 딕셔너리나 시리즈나 함수와 같이 특정값은 반드시 하나의 값을 리턴하기에 맵핑(mapping)을 할수있는 매개체

In [8]:
df2.rename(columns={'제품':'음료'})

    업체    음료    가격
0  별다방  아이스티  4500
1  별다방  카페오레  4000
2  콩다방  아이스티  6000
3  콩다방  아이스티  6000
4  콩다방  카페오레  5500

In [9]:
df1.merge(df2.rename(columns={'제품':'음료'}), how='left')

    이름   업체    음료    가격
0  송중기  별다방  아이스티  4500
1  권나현  콩다방  카페오레  5500
2  권보아  별다방  카페오레  4000
3  박효신  콩다방  아이스티  6000
4  박효신  콩다방  아이스티  6000
5  김점수  별다방  카페오레  4000