```python
df.sort_values(by,ascending=True)
```
### **by**(인수는 label 또는 lebel의 리스트)
> 정렬의 기준이 될 배열(주로 정렬의 기준인 열)을 지정하는 인자
### **ascending**(인수는 bool 또는 bool의 리스트 / 기본값은 True)
> 정렬 순서를 오름차순으로 정렬할지 내림차순으로 정렬할지 지정하는 인자

In [4]:
import pandas as pd
data = [
    [60, 84, 80, 70, 19],
    [77, 62, 95, 85, 17],
    [61, 97, 72, 67, 15],
    [75, 65, 95, 51, 18]
]

cols = ['국어', '영어', '수학', '과학', '나이']
df = pd.DataFrame(data, index=['A', 'B', 'C', 'D'], columns=cols)
df

   국어  영어  수학  과학  나이
A  60  84  80  70  19
B  77  62  95  85  17
C  61  97  72  67  15
D  75  65  95  51  18

In [10]:
df.sort_values('국어',ascending=True) # 오른차순

   국어  영어  수학  과학  나이
A  60  84  80  70  19
C  61  97  72  67  15
D  75  65  95  51  18
B  77  62  95  85  17

In [11]:
df.sort_values('영어',ascending=False) # 내림차순

   국어  영어  수학  과학  나이
C  61  97  72  67  15
A  60  84  80  70  19
D  75  65  95  51  18
B  77  62  95  85  17